In [1]:
import torch
import numpy as np
torch.cuda.is_available()

True

In [2]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

In [3]:
w = torch.tensor(1.0, requires_grad = True)
w

tensor(1., requires_grad=True)

In [4]:
# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [5]:
# backward pass
loss.backward()
w.grad

tensor(-2.)

### build the model
#### With orthogonal initialization; results in exact reconstruction

In [6]:
# input audio sequence of length N, range [-1,1]
N = 512
x = torch.rand(N)*2 - 1
x

tensor([-4.9786e-01,  3.3941e-02,  7.4277e-01, -5.7816e-01,  7.2715e-01,
         1.4110e-01,  4.5440e-01, -7.5146e-02, -6.1115e-01, -2.6269e-02,
         9.7508e-01, -8.5820e-01,  2.4998e-01, -6.4830e-01,  8.4070e-01,
        -7.5676e-01,  9.8668e-01,  9.7067e-01,  5.4432e-01, -1.8888e-01,
         1.6566e-01,  6.8023e-01, -7.4272e-01,  6.5149e-01,  6.5281e-01,
        -9.2408e-01,  5.3469e-01, -5.5026e-02, -7.5403e-01,  9.9625e-01,
        -2.4629e-01,  1.7907e-01,  4.2284e-01,  2.6352e-01,  6.9119e-01,
         8.6817e-01, -1.0740e-01,  4.5941e-01, -6.4544e-01,  4.9141e-01,
         8.3614e-01, -2.0061e-01, -8.9733e-01, -8.8943e-02, -7.4357e-01,
        -5.6306e-01, -8.8093e-01,  6.3142e-01, -7.6096e-02, -4.8484e-01,
        -2.9128e-01,  4.7271e-01,  9.4509e-01, -9.7862e-01, -2.8038e-01,
        -1.7575e-01, -6.7679e-01,  9.2533e-01,  3.5355e-01, -7.8635e-02,
        -2.2033e-01, -4.1741e-01, -2.7597e-01,  9.8922e-01,  1.3100e-01,
         3.8242e-01, -9.5709e-01,  3.8837e-02, -6.5

In [7]:
M = 512 # M <= N

#### initialize parameters

In [8]:
a1 = torch.tensor(1.0, requires_grad = True)
a2 = torch.tensor(np.sqrt(2), requires_grad = True) # sqrt(2)
a3 = torch.tensor(1.0, requires_grad = True)
a4 = torch.tensor(np.sqrt(2), requires_grad = True)
print(a1,a2,a3,a4)
print(a1.dtype)

tensor(1., requires_grad=True) tensor(1.4142, dtype=torch.float64, requires_grad=True) tensor(1., requires_grad=True) tensor(1.4142, dtype=torch.float64, requires_grad=True)
torch.float32


In [9]:
w = np.zeros((M,),dtype = np.float32)
for i in range(M):
    w[i] = (2*i+1)/(2*M)*np.pi
w

array([3.06796166e-03, 9.20388475e-03, 1.53398076e-02, 2.14757305e-02,
       2.76116543e-02, 3.37475762e-02, 3.98835018e-02, 4.60194238e-02,
       5.21553457e-02, 5.82912713e-02, 6.44271895e-02, 7.05631152e-02,
       7.66990408e-02, 8.28349590e-02, 8.89708847e-02, 9.51068103e-02,
       1.01242729e-01, 1.07378654e-01, 1.13514580e-01, 1.19650498e-01,
       1.25786424e-01, 1.31922349e-01, 1.38058275e-01, 1.44194201e-01,
       1.50330111e-01, 1.56466037e-01, 1.62601963e-01, 1.68737888e-01,
       1.74873814e-01, 1.81009740e-01, 1.87145650e-01, 1.93281576e-01,
       1.99417502e-01, 2.05553427e-01, 2.11689353e-01, 2.17825279e-01,
       2.23961189e-01, 2.30097115e-01, 2.36233041e-01, 2.42368966e-01,
       2.48504892e-01, 2.54640818e-01, 2.60776728e-01, 2.66912669e-01,
       2.73048580e-01, 2.79184490e-01, 2.85320431e-01, 2.91456342e-01,
       2.97592282e-01, 3.03728193e-01, 3.09864134e-01, 3.16000044e-01,
       3.22135955e-01, 3.28271896e-01, 3.34407806e-01, 3.40543747e-01,
      

In [10]:
w.dtype

dtype('float32')

In [11]:
w_ = np.zeros((M,),dtype = np.float32)
for i in range(M):
    w_[i] = (2*i+1)/(2*M)*np.pi

In [12]:
w1 = torch.from_numpy(w)
w2 = torch.from_numpy(w_)
w1.requires_grad_(True)
w2.requires_grad_(True)
print(w1)
print(w2.dtype)

tensor([3.0680e-03, 9.2039e-03, 1.5340e-02, 2.1476e-02, 2.7612e-02, 3.3748e-02,
        3.9884e-02, 4.6019e-02, 5.2155e-02, 5.8291e-02, 6.4427e-02, 7.0563e-02,
        7.6699e-02, 8.2835e-02, 8.8971e-02, 9.5107e-02, 1.0124e-01, 1.0738e-01,
        1.1351e-01, 1.1965e-01, 1.2579e-01, 1.3192e-01, 1.3806e-01, 1.4419e-01,
        1.5033e-01, 1.5647e-01, 1.6260e-01, 1.6874e-01, 1.7487e-01, 1.8101e-01,
        1.8715e-01, 1.9328e-01, 1.9942e-01, 2.0555e-01, 2.1169e-01, 2.1783e-01,
        2.2396e-01, 2.3010e-01, 2.3623e-01, 2.4237e-01, 2.4850e-01, 2.5464e-01,
        2.6078e-01, 2.6691e-01, 2.7305e-01, 2.7918e-01, 2.8532e-01, 2.9146e-01,
        2.9759e-01, 3.0373e-01, 3.0986e-01, 3.1600e-01, 3.2214e-01, 3.2827e-01,
        3.3441e-01, 3.4054e-01, 3.4668e-01, 3.5282e-01, 3.5895e-01, 3.6509e-01,
        3.7122e-01, 3.7736e-01, 3.8350e-01, 3.8963e-01, 3.9577e-01, 4.0190e-01,
        4.0804e-01, 4.1417e-01, 4.2031e-01, 4.2645e-01, 4.3258e-01, 4.3872e-01,
        4.4485e-01, 4.5099e-01, 4.5713e-

#### forward pass and compute the loss

In [13]:
# weight matrix W1
W1 = torch.zeros(M,N)
for m in range(M):
    W1[m,0] = a1
    for n in range(1,N):
        W1[m,n] = a2 * torch.cos(w1[m]*n)
W1

tensor([[ 1.0000,  1.4142,  1.4142,  ...,  0.0130,  0.0087,  0.0043],
        [ 1.0000,  1.4142,  1.4140,  ..., -0.0390, -0.0260, -0.0130],
        [ 1.0000,  1.4140,  1.4135,  ...,  0.0651,  0.0434,  0.0217],
        ...,
        [ 1.0000, -1.4140,  1.4135,  ..., -0.0651,  0.0433, -0.0218],
        [ 1.0000, -1.4142,  1.4140,  ...,  0.0390, -0.0261,  0.0130],
        [ 1.0000, -1.4142,  1.4142,  ..., -0.0131,  0.0087, -0.0044]],
       grad_fn=<CopySlices>)

In [14]:
# frequency domain X
X = torch.matmul(W1,x)/np.sqrt(N)
X

tensor([ 5.9314e-01,  7.7775e-01, -7.7766e-01,  4.4216e-01, -1.5824e-02,
        -6.2698e-01,  1.4201e+00,  4.2208e-01,  5.0073e-01, -7.4016e-01,
         1.5246e-01,  6.6276e-01, -3.4127e-01,  5.6639e-01,  9.1497e-02,
        -7.5788e-01,  1.0320e-01, -6.8031e-01, -1.0918e-01,  2.4517e-01,
        -3.6774e-01, -9.4777e-01, -3.1896e-02,  4.9973e-01,  2.5235e-01,
         1.4203e-01, -1.4377e+00, -4.3928e-01,  3.9387e-01,  9.3811e-01,
        -9.1157e-01, -4.4804e-02,  5.5892e-01,  1.5907e+00,  3.9329e-01,
        -9.4202e-01,  3.1304e-01, -1.9044e-01, -5.2601e-01,  5.6149e-01,
        -8.6673e-01, -3.2995e-01,  2.1085e-01,  7.1997e-01, -7.3018e-02,
        -4.6153e-01, -7.1423e-01, -2.5334e-01, -4.9120e-01,  6.8642e-01,
         8.1922e-02, -2.1562e-01,  2.9496e-01,  5.4191e-01,  1.0059e-01,
        -8.4804e-02,  7.3876e-01,  9.8476e-01,  2.3622e-01, -5.9466e-01,
         6.2985e-01,  6.6080e-02, -3.2289e-02,  1.1610e+00,  1.9176e-01,
         2.1228e-01, -1.4559e-01, -1.2669e+00,  6.5

In [15]:
np.max(X.detach().numpy())

1.8740975

In [16]:
# weight matrix W2_1 with same frequency components w1
W2_1 = torch.zeros(N,M)
for m in range(M):
    W2_1[0,m] = a3
    for n in range(1,N):
        W2_1[n,m] = a4 * torch.cos(w1[m]*n)
W2_1

tensor([[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 1.4142,  1.4142,  1.4140,  ..., -1.4140, -1.4142, -1.4142],
        [ 1.4142,  1.4140,  1.4135,  ...,  1.4135,  1.4140,  1.4142],
        ...,
        [ 0.0130, -0.0390,  0.0651,  ..., -0.0651,  0.0390, -0.0131],
        [ 0.0087, -0.0260,  0.0434,  ...,  0.0433, -0.0261,  0.0087],
        [ 0.0043, -0.0130,  0.0217,  ..., -0.0218,  0.0130, -0.0044]],
       grad_fn=<CopySlices>)

In [17]:
# weight matrix W2_2 with different frequency components w2
W2_2 = torch.zeros(N,M)
for m in range(M):
    W2_2[0,m] = a3
    for n in range(1,N):
        W2_2[n,m] = a4 * torch.cos(w2[m]*n)
W2_2

tensor([[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 1.4142,  1.4142,  1.4140,  ..., -1.4140, -1.4142, -1.4142],
        [ 1.4142,  1.4140,  1.4135,  ...,  1.4135,  1.4140,  1.4142],
        ...,
        [ 0.0130, -0.0390,  0.0651,  ..., -0.0651,  0.0390, -0.0131],
        [ 0.0087, -0.0260,  0.0434,  ...,  0.0433, -0.0261,  0.0087],
        [ 0.0043, -0.0130,  0.0217,  ..., -0.0218,  0.0130, -0.0044]],
       grad_fn=<CopySlices>)

In [18]:
y = torch.matmul(W2_1,X)/np.sqrt(N)
np.max(y.detach().numpy())

0.9962496

In [19]:
y

tensor([-4.9787e-01,  3.3948e-02,  7.4275e-01, -5.7815e-01,  7.2716e-01,
         1.4111e-01,  4.5438e-01, -7.5137e-02, -6.1114e-01, -2.6285e-02,
         9.7508e-01, -8.5820e-01,  2.4999e-01, -6.4830e-01,  8.4070e-01,
        -7.5676e-01,  9.8668e-01,  9.7067e-01,  5.4433e-01, -1.8888e-01,
         1.6567e-01,  6.8022e-01, -7.4272e-01,  6.5148e-01,  6.5282e-01,
        -9.2408e-01,  5.3469e-01, -5.5017e-02, -7.5404e-01,  9.9625e-01,
        -2.4628e-01,  1.7906e-01,  4.2285e-01,  2.6352e-01,  6.9119e-01,
         8.6817e-01, -1.0740e-01,  4.5940e-01, -6.4543e-01,  4.9141e-01,
         8.3614e-01, -2.0061e-01, -8.9734e-01, -8.8949e-02, -7.4354e-01,
        -5.6307e-01, -8.8092e-01,  6.3143e-01, -7.6105e-02, -4.8484e-01,
        -2.9127e-01,  4.7270e-01,  9.4509e-01, -9.7862e-01, -2.8037e-01,
        -1.7575e-01, -6.7679e-01,  9.2532e-01,  3.5356e-01, -7.8628e-02,
        -2.2034e-01, -4.1741e-01, -2.7596e-01,  9.8922e-01,  1.3100e-01,
         3.8241e-01, -9.5709e-01,  3.8826e-02, -6.5

In [20]:
x

tensor([-4.9786e-01,  3.3941e-02,  7.4277e-01, -5.7816e-01,  7.2715e-01,
         1.4110e-01,  4.5440e-01, -7.5146e-02, -6.1115e-01, -2.6269e-02,
         9.7508e-01, -8.5820e-01,  2.4998e-01, -6.4830e-01,  8.4070e-01,
        -7.5676e-01,  9.8668e-01,  9.7067e-01,  5.4432e-01, -1.8888e-01,
         1.6566e-01,  6.8023e-01, -7.4272e-01,  6.5149e-01,  6.5281e-01,
        -9.2408e-01,  5.3469e-01, -5.5026e-02, -7.5403e-01,  9.9625e-01,
        -2.4629e-01,  1.7907e-01,  4.2284e-01,  2.6352e-01,  6.9119e-01,
         8.6817e-01, -1.0740e-01,  4.5941e-01, -6.4544e-01,  4.9141e-01,
         8.3614e-01, -2.0061e-01, -8.9733e-01, -8.8943e-02, -7.4357e-01,
        -5.6306e-01, -8.8093e-01,  6.3142e-01, -7.6096e-02, -4.8484e-01,
        -2.9128e-01,  4.7271e-01,  9.4509e-01, -9.7862e-01, -2.8038e-01,
        -1.7575e-01, -6.7679e-01,  9.2533e-01,  3.5355e-01, -7.8635e-02,
        -2.2033e-01, -4.1741e-01, -2.7597e-01,  9.8922e-01,  1.3100e-01,
         3.8242e-01, -9.5709e-01,  3.8837e-02, -6.5

In [21]:
err = ((x-y)**2).mean()
err

tensor(2.4233e-10, grad_fn=<MeanBackward0>)